In [31]:
import zipfile
from pathlib import Path
import pandas as pd
import os

data_path= Path('Data/')

data_zip=data_path/'DataFiles.zip'
zip_ref = zipfile.ZipFile(data_zip, 'r')
data_csv_path=data_path/'DataFiles'
zip_ref.extractall(data_csv_path)
cities=pd.read_csv(data_csv_path/'Cities.csv')
os.remove(data_csv_path/'Cities.csv')
conferences=pd.read_csv(data_csv_path/'Conferences.csv')
os.remove(data_csv_path/'Conferences.csv')
team_conferences=pd.read_csv(data_csv_path/'TeamConferences.csv')
os.remove(data_csv_path/'TeamConferences.csv')
conference_tourney_games=pd.read_csv(data_csv_path/'ConferenceTourneyGames.csv')
os.remove(data_csv_path/'ConferenceTourneyGames.csv')
game_cites=pd.read_csv(data_csv_path/'GameCities.csv')
os.remove(data_csv_path/'GameCities.csv')
ncaa_tourney_compact_results=pd.read_csv(data_csv_path/'NCAATourneyCompactResults.csv')
os.remove(data_csv_path/'NCAATourneyCompactResults.csv')
ncaa_tourney_detailed_results=pd.read_csv(data_csv_path/'NCAATourneyDetailedResults.csv')
os.remove(data_csv_path/'NCAATourneyDetailedResults.csv')
ncaa_tourney_seed_round_slots=pd.read_csv(data_csv_path/'NCAATourneySeedRoundSlots.csv')
os.remove(data_csv_path/'NCAATourneySeedRoundSlots.csv')
ncaa_tourney_seeds=pd.read_csv(data_csv_path/'NCAATourneySeeds.csv')
os.remove(data_csv_path/'NCAATourneySeeds.csv')
ncaa_tourney_slots=pd.read_csv(data_csv_path/'NCAATourneySlots.csv')
os.remove(data_csv_path/'NCAATourneySlots.csv')
regular_season_compact_results=pd.read_csv(data_csv_path/'RegularSeasonCompactResults.csv')
os.remove(data_csv_path/'RegularSeasonCompactResults.csv')
regular_season_detailed_results=pd.read_csv(data_csv_path/'RegularSeasonDetailedResults.csv')
os.remove(data_csv_path/'RegularSeasonDetailedResults.csv')
seasons=pd.read_csv(data_csv_path/'Seasons.csv')
os.remove(data_csv_path/'Seasons.csv')
secondary_tourney_compact_results=pd.read_csv(data_csv_path/'SecondaryTourneyCompactResults.csv')
os.remove(data_csv_path/'SecondaryTourneyCompactResults.csv')
secondary_tourney_teams=pd.read_csv(data_csv_path/'SecondaryTourneyTeams.csv')
os.remove(data_csv_path/'SecondaryTourneyTeams.csv')
team_coaches=pd.read_csv(data_csv_path/'TeamCoaches.csv')
os.remove(data_csv_path/'TeamCoaches.csv')
teams=pd.read_csv(data_csv_path/'Teams.csv')
os.remove(data_csv_path/'Teams.csv')
#Below line has an encoding error
#team_spelling=pd.read_csv(data_csv_path/'TeamSpellings.csv')
os.remove(data_csv_path/'TeamSpellings.csv')
os.removedirs(data_csv_path)


Massey_Ordinals_zip=data_path/'MasseyOrdinals.zip'
zip_ref = zipfile.ZipFile(Massey_Ordinals_zip, 'r')
massey_ordinals_csv_path=data_path/'MasseyOrdinals'
zip_ref.extractall(massey_ordinals_csv_path)
massey_ordinals=pd.read_csv(massey_ordinals_csv_path/'MasseyOrdinals.csv')
os.remove(massey_ordinals_csv_path/'MasseyOrdinals.csv')
os.removedirs(massey_ordinals_csv_path)

PBP_2010_zip=data_path/'PlayByPlay_2010.zip'
zip_ref = zipfile.ZipFile(PBP_2010_zip, 'r')
PBP_2010_csv_path=data_path/'PlayByPlay_2010'
zip_ref.extractall(PBP_2010_csv_path)
events_2010=pd.read_csv(PBP_2010_csv_path/'Events_2010.csv')
os.remove(PBP_2010_csv_path/'Events_2010.csv')
players_2010=pd.read_csv(PBP_2010_csv_path/'Players_2010.csv')
os.remove(PBP_2010_csv_path/'Players_2010.csv')
os.removedirs(PBP_2010_csv_path)

PBP_2011_zip=data_path/'PlayByPlay_2011.zip'
zip_ref = zipfile.ZipFile(PBP_2011_zip, 'r')
PBP_2011_csv_path=data_path/'PlayByPlay_2011'
zip_ref.extractall(PBP_2011_csv_path)
events_2011=pd.read_csv(PBP_2011_csv_path/'Events_2011.csv')
os.remove(PBP_2011_csv_path/'Events_2011.csv')
players_2011=pd.read_csv(PBP_2011_csv_path/'Players_2011.csv')
os.remove(PBP_2011_csv_path/'Players_2011.csv')
os.removedirs(PBP_2011_csv_path)

PBP_2012_zip=data_path/'PlayByPlay_2012.zip'
zip_ref = zipfile.ZipFile(PBP_2012_zip, 'r')
PBP_2012_csv_path=data_path/'PlayByPlay_2012'
zip_ref.extractall(PBP_2012_csv_path)
events_2012=pd.read_csv(PBP_2012_csv_path/'Events_2012.csv')
os.remove(PBP_2012_csv_path/'Events_2012.csv')
players_2012=pd.read_csv(PBP_2012_csv_path/'Players_2012.csv')
os.remove(PBP_2012_csv_path/'Players_2012.csv')
os.removedirs(PBP_2012_csv_path)

PBP_2013_zip=data_path/'PlayByPlay_2013.zip'
zip_ref = zipfile.ZipFile(PBP_2013_zip, 'r')
PBP_2013_csv_path=data_path/'PlayByPlay_2013'
zip_ref.extractall(PBP_2013_csv_path)
events_2013=pd.read_csv(PBP_2013_csv_path/'Events_2013.csv')
os.remove(PBP_2013_csv_path/'Events_2013.csv')
players_2013=pd.read_csv(PBP_2013_csv_path/'Players_2013.csv')
os.remove(PBP_2013_csv_path/'Players_2013.csv')
os.removedirs(PBP_2013_csv_path)

PBP_2014_zip=data_path/'PlayByPlay_2014.zip'
zip_ref = zipfile.ZipFile(PBP_2014_zip, 'r')
PBP_2014_csv_path=data_path/'PlayByPlay_2014'
zip_ref.extractall(PBP_2014_csv_path)
events_2014=pd.read_csv(PBP_2014_csv_path/'Events_2014.csv')
os.remove(PBP_2014_csv_path/'Events_2014.csv')
players_2014=pd.read_csv(PBP_2014_csv_path/'Players_2014.csv')
os.remove(PBP_2014_csv_path/'Players_2014.csv')
os.removedirs(PBP_2014_csv_path)

PBP_2015_zip=data_path/'PlayByPlay_2015.zip'
zip_ref = zipfile.ZipFile(PBP_2015_zip, 'r')
PBP_2015_csv_path=data_path/'PlayByPlay_2015'
zip_ref.extractall(PBP_2015_csv_path)
events_2015=pd.read_csv(PBP_2015_csv_path/'Events_2015.csv')
os.remove(PBP_2015_csv_path/'Events_2015.csv')
players_2015=pd.read_csv(PBP_2015_csv_path/'Players_2015.csv')
os.remove(PBP_2015_csv_path/'Players_2015.csv')
os.removedirs(PBP_2015_csv_path)

PBP_2016_zip=data_path/'PlayByPlay_2016.zip'
zip_ref = zipfile.ZipFile(PBP_2016_zip, 'r')
PBP_2016_csv_path=data_path/'PlayByPlay_2016'
zip_ref.extractall(PBP_2016_csv_path)
events_2016=pd.read_csv(PBP_2016_csv_path/'Events_2016.csv')
os.remove(PBP_2016_csv_path/'Events_2016.csv')
players_2016=pd.read_csv(PBP_2016_csv_path/'Players_2016.csv')
os.remove(PBP_2016_csv_path/'Players_2016.csv')
os.removedirs(PBP_2016_csv_path)

PBP_2017_zip=data_path/'PlayByPlay_2017.zip'
zip_ref = zipfile.ZipFile(PBP_2017_zip, 'r')
PBP_2017_csv_path=data_path/'PlayByPlay_2017'
zip_ref.extractall(PBP_2017_csv_path)
events_2017=pd.read_csv(PBP_2017_csv_path/'Events_2017.csv')
os.remove(PBP_2017_csv_path/'Events_2017.csv')
players_2017=pd.read_csv(PBP_2017_csv_path/'Players_2017.csv')
os.remove(PBP_2017_csv_path/'Players_2017.csv')
os.removedirs(PBP_2017_csv_path)

,EventID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,ElapsedSeconds,EventTeamID,EventPlayerID,EventType
0,20434640,2017,11,1104,1157,0,0,0,1104,637419,sub_in
1,20434641,2017,11,1104,1157,0,0,15,1157,638145,foul_pers
2,20434642,2017,11,1104,1157,0,0,15,1157,638145,turnover
3,20434643,2017,11,1104,1157,0,0,26,1104,637423,assist
4,20434644,2017,11,1104,1157,3,0,26,1104,637420,made3_jump
5,20434645,2017,11,1104,1157,0,0,63,1157,638145,miss2_jump
6,20434646,2017,11,1104,1157,0,0,63,1104,637415,reb_def
7,20434647,2017,11,1104,1157,0,0,68,1104,637410,miss3_jump
8,20434648,2017,11,1104,1157,0,0,68,1157,638150,reb_def
9,20434649,2017,11,1104,1157,0,0,77,1104,637410,foul_pers
10,20434650,2017,11,1104,1157,0,0,82,1157,638155,foul_pers
11,20434651,2017,11,1104,1157,0,0,82,1157,638155,turnover
12,20434652,2017,11,1104,1157,0,0,96,1157,638156,foul_pers
13,20434653,2017,11,1104,1157,0,0,121,1104,637423,turnover
14,20434654,2017,11,1104,1157,0,0,136,1157,638156,turnover
15,20434655,2017,11,1104,1157,0,0,138,1104,637423,steal
16,20434656,2017,11,1104,1157,0,0,146,1104,637410,miss3_jump
17,20434657,2017,11,1104,1157,0,0,146,1157,638153,reb_def
18,20434658,2017,11,1104,1157,0,0,148,1104,637423,foul_pers
19,20434659,2017,11,1104,1157,0,0,165,1157,638156,miss2_jump
20,20434660,2017,11,1104,1157,0,0,166,1104,637423,reb_def
21,20434661,2017,11,1104,1157,0,0,177,1157,638155,foul_pers
22,20434662,2017,11,1104,1157,0,0,177,1157,638144,sub_in
23,20434663,2017,11,1104,1157,0,0,177,1157,638152,sub_in
24,20434664,2017,11,1104,1157,0,0,177,1157,638151,sub_out
25,20434665,2017,11,1104,1157,0,0,177,1157,638155,sub_out
26,20434666,2017,11,1104,1157,4,0,177,1104,637413,made1_free
27,20434667,2017,11,1104,1157,5,0,177,1104,637413,made1_free
28,20434668,2017,11,1104,1157,0,0,201,1157,638150,miss2_jump
29,20434669,2017,11,1104,1157,0,0,201,1157,638150,reb_off
...,...,...,...,...,...,...,...,...,...,...,...
2543949,22978589,2017,152,1314,1332,0,0,2322,1332,640781,timeout
2543950,22978590,2017,152,1314,1332,0,0,2326,1332,640768,sub_in
2543951,22978591,2017,152,1314,1332,0,0,2326,1332,640779,sub_out
2543952,22978592,2017,152,1314,1332,0,0,2326,1314,640514,turnover
2543953,22978593,2017,152,1314,1332,0,0,2335,1332,640778,miss3_jump
2543954,22978594,2017,152,1314,1332,0,0,2335,1314,640507,reb_def
2543955,22978595,2017,152,1314,1332,0,0,2343,1332,640774,foul_pers
2543956,22978596,2017,152,1314,1332,76,71,2343,1314,640517,made1_free
2543957,22978597,2017,152,1314,1332,77,71,2343,1314,640517,made1_free
2543958,22978598,2017,152,1314,1332,0,0,2347,1332,640774,miss3_jump
2543959,22978599,2017,152,1314,1332,0,0,2347,1332,640778,reb_off
2543960,22978600,2017,152,1314,1332,0,0,2355,1332,640767,assist
2543961,22978601,2017,152,1314,1332,77,74,2355,1332,640774,made3_jump
2543962,22978602,2017,152,1314,1332,0,0,2358,1332,640779,sub_in
2543963,22978603,2017,152,1314,1332,0,0,2358,1332,640768,sub_out
2543964,22978604,2017,152,1314,1332,0,0,2358,1332,640781,timeout
2543965,22978605,2017,152,1314,1332,0,0,2382,1314,640517,miss2_jump
2543966,22978606,2017,152,1314,1332,0,0,2382,1332,640767,reb_def
2543967,22978607,2017,152,1314,1332,0,0,2393,1332,640775,assist
2543968,22978608,2017,152,1314,1332,77,76,2393,1332,640779,made2_lay
2543969,22978609,2017,152,1314,1332,0,0,2395,1332,640774,foul_pers
2543970,22978610,2017,152,1314,1332,0,0,2395,1314,640516,miss1_free
2543971,22978611,2017,152,1314,1332,0,0,2395,1314,640521,reb_dead
2543972,22978612,2017,152,1314,1332,0,0,2395,1314,640517,reb_off
2543973,22978613,2017,152,1314,1332,0,0,2395,1332,640768,sub_in
2543974,22978614,2017,152,1314,1332,0,0,2395,1332,640779,sub_out
2543975,22978615,2017,152,1314,1332,0,0,2396,1332,640778,foul_pers
2543976,22978616,2017,152,1314,1332,0,0,2396,1314,640507,miss1_free
2543977,22978617,2017,152,1314,1332,0,0,2396,1314,640521,reb_dead
2543978,22978618,2017,152,1314,1332,0,0,2396,1314,640516,reb_off