In [136]:
import zipfile
from pathlib import Path
import pandas as pd
import os

data_path= Path('Data/')

sample_submission=pd.read_csv(data_path/'SampleSubmissionStage1.csv')

data_zip=data_path/'DataFiles.zip'
zip_ref = zipfile.ZipFile(data_zip, 'r')
data_csv_path=data_path/'DataFiles'
zip_ref.extractall(data_csv_path)
cities=pd.read_csv(data_csv_path/'Cities.csv')
os.remove(data_csv_path/'Cities.csv')
conferences=pd.read_csv(data_csv_path/'Conferences.csv')
os.remove(data_csv_path/'Conferences.csv')
team_conferences=pd.read_csv(data_csv_path/'TeamConferences.csv')
os.remove(data_csv_path/'TeamConferences.csv')
conference_tourney_games=pd.read_csv(data_csv_path/'ConferenceTourneyGames.csv')
os.remove(data_csv_path/'ConferenceTourneyGames.csv')
game_cites=pd.read_csv(data_csv_path/'GameCities.csv')
os.remove(data_csv_path/'GameCities.csv')
ncaa_tourney_compact_results=pd.read_csv(data_csv_path/'NCAATourneyCompactResults.csv')
os.remove(data_csv_path/'NCAATourneyCompactResults.csv')
ncaa_tourney_detailed_results=pd.read_csv(data_csv_path/'NCAATourneyDetailedResults.csv')
os.remove(data_csv_path/'NCAATourneyDetailedResults.csv')
ncaa_tourney_seed_round_slots=pd.read_csv(data_csv_path/'NCAATourneySeedRoundSlots.csv')
os.remove(data_csv_path/'NCAATourneySeedRoundSlots.csv')
ncaa_tourney_seeds=pd.read_csv(data_csv_path/'NCAATourneySeeds.csv')
os.remove(data_csv_path/'NCAATourneySeeds.csv')
ncaa_tourney_slots=pd.read_csv(data_csv_path/'NCAATourneySlots.csv')
os.remove(data_csv_path/'NCAATourneySlots.csv')
regular_season_compact_results=pd.read_csv(data_csv_path/'RegularSeasonCompactResults.csv')
os.remove(data_csv_path/'RegularSeasonCompactResults.csv')
regular_season_detailed_results=pd.read_csv(data_csv_path/'RegularSeasonDetailedResults.csv')
os.remove(data_csv_path/'RegularSeasonDetailedResults.csv')
seasons=pd.read_csv(data_csv_path/'Seasons.csv')
os.remove(data_csv_path/'Seasons.csv')
secondary_tourney_compact_results=pd.read_csv(data_csv_path/'SecondaryTourneyCompactResults.csv')
os.remove(data_csv_path/'SecondaryTourneyCompactResults.csv')
secondary_tourney_teams=pd.read_csv(data_csv_path/'SecondaryTourneyTeams.csv')
os.remove(data_csv_path/'SecondaryTourneyTeams.csv')
team_coaches=pd.read_csv(data_csv_path/'TeamCoaches.csv')
os.remove(data_csv_path/'TeamCoaches.csv')
teams=pd.read_csv(data_csv_path/'Teams.csv')
os.remove(data_csv_path/'Teams.csv')
#Below line has an encoding error
#team_spelling=pd.read_csv(data_csv_path/'TeamSpellings.csv')
os.remove(data_csv_path/'TeamSpellings.csv')
os.removedirs(data_csv_path)


Massey_Ordinals_zip=data_path/'MasseyOrdinals.zip'
zip_ref = zipfile.ZipFile(Massey_Ordinals_zip, 'r')
massey_ordinals_csv_path=data_path/'MasseyOrdinals'
zip_ref.extractall(massey_ordinals_csv_path)
massey_ordinals=pd.read_csv(massey_ordinals_csv_path/'MasseyOrdinals.csv')
os.remove(massey_ordinals_csv_path/'MasseyOrdinals.csv')
os.removedirs(massey_ordinals_csv_path)

PBP_2010_zip=data_path/'PlayByPlay_2010.zip'
zip_ref = zipfile.ZipFile(PBP_2010_zip, 'r')
PBP_2010_csv_path=data_path/'PlayByPlay_2010'
zip_ref.extractall(PBP_2010_csv_path)
events_2010=pd.read_csv(PBP_2010_csv_path/'Events_2010.csv')
os.remove(PBP_2010_csv_path/'Events_2010.csv')
players_2010=pd.read_csv(PBP_2010_csv_path/'Players_2010.csv')
os.remove(PBP_2010_csv_path/'Players_2010.csv')
os.removedirs(PBP_2010_csv_path)

PBP_2011_zip=data_path/'PlayByPlay_2011.zip'
zip_ref = zipfile.ZipFile(PBP_2011_zip, 'r')
PBP_2011_csv_path=data_path/'PlayByPlay_2011'
zip_ref.extractall(PBP_2011_csv_path)
events_2011=pd.read_csv(PBP_2011_csv_path/'Events_2011.csv')
os.remove(PBP_2011_csv_path/'Events_2011.csv')
players_2011=pd.read_csv(PBP_2011_csv_path/'Players_2011.csv')
os.remove(PBP_2011_csv_path/'Players_2011.csv')
os.removedirs(PBP_2011_csv_path)

PBP_2012_zip=data_path/'PlayByPlay_2012.zip'
zip_ref = zipfile.ZipFile(PBP_2012_zip, 'r')
PBP_2012_csv_path=data_path/'PlayByPlay_2012'
zip_ref.extractall(PBP_2012_csv_path)
events_2012=pd.read_csv(PBP_2012_csv_path/'Events_2012.csv')
os.remove(PBP_2012_csv_path/'Events_2012.csv')
players_2012=pd.read_csv(PBP_2012_csv_path/'Players_2012.csv')
os.remove(PBP_2012_csv_path/'Players_2012.csv')
os.removedirs(PBP_2012_csv_path)

PBP_2013_zip=data_path/'PlayByPlay_2013.zip'
zip_ref = zipfile.ZipFile(PBP_2013_zip, 'r')
PBP_2013_csv_path=data_path/'PlayByPlay_2013'
zip_ref.extractall(PBP_2013_csv_path)
events_2013=pd.read_csv(PBP_2013_csv_path/'Events_2013.csv')
os.remove(PBP_2013_csv_path/'Events_2013.csv')
players_2013=pd.read_csv(PBP_2013_csv_path/'Players_2013.csv')
os.remove(PBP_2013_csv_path/'Players_2013.csv')
os.removedirs(PBP_2013_csv_path)

PBP_2014_zip=data_path/'PlayByPlay_2014.zip'
zip_ref = zipfile.ZipFile(PBP_2014_zip, 'r')
PBP_2014_csv_path=data_path/'PlayByPlay_2014'
zip_ref.extractall(PBP_2014_csv_path)
events_2014=pd.read_csv(PBP_2014_csv_path/'Events_2014.csv')
os.remove(PBP_2014_csv_path/'Events_2014.csv')
players_2014=pd.read_csv(PBP_2014_csv_path/'Players_2014.csv')
os.remove(PBP_2014_csv_path/'Players_2014.csv')
os.removedirs(PBP_2014_csv_path)

PBP_2015_zip=data_path/'PlayByPlay_2015.zip'
zip_ref = zipfile.ZipFile(PBP_2015_zip, 'r')
PBP_2015_csv_path=data_path/'PlayByPlay_2015'
zip_ref.extractall(PBP_2015_csv_path)
events_2015=pd.read_csv(PBP_2015_csv_path/'Events_2015.csv')
os.remove(PBP_2015_csv_path/'Events_2015.csv')
players_2015=pd.read_csv(PBP_2015_csv_path/'Players_2015.csv')
os.remove(PBP_2015_csv_path/'Players_2015.csv')
os.removedirs(PBP_2015_csv_path)

PBP_2016_zip=data_path/'PlayByPlay_2016.zip'
zip_ref = zipfile.ZipFile(PBP_2016_zip, 'r')
PBP_2016_csv_path=data_path/'PlayByPlay_2016'
zip_ref.extractall(PBP_2016_csv_path)
events_2016=pd.read_csv(PBP_2016_csv_path/'Events_2016.csv')
os.remove(PBP_2016_csv_path/'Events_2016.csv')
players_2016=pd.read_csv(PBP_2016_csv_path/'Players_2016.csv')
os.remove(PBP_2016_csv_path/'Players_2016.csv')
os.removedirs(PBP_2016_csv_path)

PBP_2017_zip=data_path/'PlayByPlay_2017.zip'
zip_ref = zipfile.ZipFile(PBP_2017_zip, 'r')
PBP_2017_csv_path=data_path/'PlayByPlay_2017'
zip_ref.extractall(PBP_2017_csv_path)
events_2017=pd.read_csv(PBP_2017_csv_path/'Events_2017.csv')
os.remove(PBP_2017_csv_path/'Events_2017.csv')
players_2017=pd.read_csv(PBP_2017_csv_path/'Players_2017.csv')
os.remove(PBP_2017_csv_path/'Players_2017.csv')
os.removedirs(PBP_2017_csv_path)

In [137]:
massey_ordinals

         Season  RankingDayNum SystemName  TeamID  OrdinalRank
0          2003             35        SEL    1102          159
1          2003             35        SEL    1103          229
2          2003             35        SEL    1104           12
3          2003             35        SEL    1105          314
4          2003             35        SEL    1106          260
5          2003             35        SEL    1107          249
6          2003             35        SEL    1108          228
7          2003             35        SEL    1110          204
8          2003             35        SEL    1111          183
9          2003             35        SEL    1112           26
10         2003             35        SEL    1113           89
11         2003             35        SEL    1114          110
12         2003             35        SEL    1115          287
13         2003             35        SEL    1116          143
14         2003             35        SEL    1117          255
15         2003             35        SEL    1119          318
16         2003             35        SEL    1120           74
17         2003             35        SEL    1122          111
18         2003             35        SEL    1123           40
19         2003             35        SEL    1124           91
20         2003             35        SEL    1125          163
21         2003             35        SEL    1126          203
22         2003             35        SEL    1127          173
23         2003             35        SEL    1128          220
24         2003             35        SEL    1129          139
25         2003             35        SEL    1130           64
26         2003             35        SEL    1131           83
27         2003             35        SEL    1132          270
28         2003             35        SEL    1133          200
29         2003             35        SEL    1135          279
...         ...            ...        ...     ...          ...
3200171    2017            133        ZAM    1433           52
3200172    2017            133        ZAM    1434           96
3200173    2017            133        ZAM    1435           44
3200174    2017            133        ZAM    1436           64
3200175    2017            133        ZAM    1437            1
3200176    2017            133        ZAM    1438            3
3200177    2017            133        ZAM    1439           48
3200178    2017            133        ZAM    1440          324
3200179    2017            133        ZAM    1441          319
3200180    2017            133        ZAM    1442          296
3200181    2017            133        ZAM    1443          240
3200182    2017            133        ZAM    1444          163
3200183    2017            133        ZAM    1447          256
3200184    2017            133        ZAM    1448           34
3200185    2017            133        ZAM    1449          149
3200186    2017            133        ZAM    1450          188
3200187    2017            133        ZAM    1451          142
3200188    2017            133        ZAM    1452            6
3200189    2017            133        ZAM    1453          184
3200190    2017            133        ZAM    1454          233
3200191    2017            133        ZAM    1455           10
3200192    2017            133        ZAM    1456          154
3200193    2017            133        ZAM    1457          120
3200194    2017            133        ZAM    1458           14
3200195    2017            133        ZAM    1459          136
3200196    2017            133        ZAM    1460          175
3200197    2017            133        ZAM    1461          143
3200198    2017            133        ZAM    1462           39
3200199    2017            133        ZAM    1463          172
3200200    2017            133        ZAM    1464          283

[3200201 rows x 5 columns]

In [138]:
ncaa_tourney_seed_round_slots

     Seed  GameRound GameSlot  EarlyDayNum  LateDayNum
0     W01          1     R1W1          136         137
1     W01          2     R2W1          138         139
2     W01          3     R3W1          143         144
3     W01          4     R4W1          145         146
4     W01          5     R5WX          152         152
5     W01          6     R6CH          154         154
6     W02          1     R1W2          136         137
7     W02          2     R2W2          138         139
8     W02          3     R3W2          143         144
9     W02          4     R4W1          145         146
10    W02          5     R5WX          152         152
11    W02          6     R6CH          154         154
12    W03          1     R1W3          136         137
13    W03          2     R2W3          138         139
14    W03          3     R3W2          143         144
15    W03          4     R4W1          145         146
16    W03          5     R5WX          152         152
17    W03          6     R6CH          154         154
18    W04          1     R1W4          136         137
19    W04          2     R2W4          138         139
20    W04          3     R3W1          143         144
21    W04          4     R4W1          145         146
22    W04          5     R5WX          152         152
23    W04          6     R6CH          154         154
24    W05          1     R1W5          136         137
25    W05          2     R2W4          138         139
26    W05          3     R3W1          143         144
27    W05          4     R4W1          145         146
28    W05          5     R5WX          152         152
29    W05          6     R6CH          154         154
..    ...        ...      ...          ...         ...
690  Z15a          4     R4Z1          145         146
691  Z15a          5     R5YZ          152         152
692  Z15a          6     R6CH          154         154
693  Z15b          0      Z15          134         135
694  Z15b          1     R1Z2          136         137
695  Z15b          2     R2Z2          138         139
696  Z15b          3     R3Z2          143         144
697  Z15b          4     R4Z1          145         146
698  Z15b          5     R5YZ          152         152
699  Z15b          6     R6CH          154         154
700   Z16          1     R1Z1          136         137
701   Z16          2     R2Z1          138         139
702   Z16          3     R3Z1          143         144
703   Z16          4     R4Z1          145         146
704   Z16          5     R5YZ          152         152
705   Z16          6     R6CH          154         154
706  Z16a          0      Z16          134         135
707  Z16a          1     R1Z1          136         137
708  Z16a          2     R2Z1          138         139
709  Z16a          3     R3Z1          143         144
710  Z16a          4     R4Z1          145         146
711  Z16a          5     R5YZ          152         152
712  Z16a          6     R6CH          154         154
713  Z16b          0      Z16          134         135
714  Z16b          1     R1Z1          136         137
715  Z16b          2     R2Z1          138         139
716  Z16b          3     R3Z1          143         144
717  Z16b          4     R4Z1          145         146
718  Z16b          5     R5YZ          152         152
719  Z16b          6     R6CH          154         154

[720 rows x 5 columns]

In [139]:
teams

     TeamID         TeamName  FirstD1Season  LastD1Season
0      1101      Abilene Chr           2014          2018
1      1102        Air Force           1985          2018
2      1103            Akron           1985          2018
3      1104          Alabama           1985          2018
4      1105      Alabama A&M           2000          2018
5      1106       Alabama St           1985          2018
6      1107        Albany NY           2000          2018
7      1108        Alcorn St           1985          2018
8      1109     Alliant Intl           1985          1991
9      1110    American Univ           1985          2018
10     1111   Appalachian St           1985          2018
11     1112          Arizona           1985          2018
12     1113       Arizona St           1985          2018
13     1114  Ark Little Rock           1985          2018
14     1115   Ark Pine Bluff           1999          2018
15     1116         Arkansas           1985          2018
16     1117      Arkansas St           1985          2018
17     1118     Armstrong St           1987          1987
18     1119             Army           1985          2018
19     1120           Auburn           1985          2018
20     1121          Augusta           1985          1991
21     1122      Austin Peay           1985          2018
22     1123          Ball St           1985          2018
23     1124           Baylor           1985          2018
24     1125          Belmont           2000          2018
25     1126  Bethune-Cookman           1985          2018
26     1127       Binghamton           2002          2018
27     1128    Birmingham So           2003          2006
28     1129         Boise St           1985          2018
29     1130   Boston College           1985          2018
..      ...              ...            ...           ...
334    1435       Vanderbilt           1985          2018
335    1436          Vermont           1985          2018
336    1437        Villanova           1985          2018
337    1438         Virginia           1985          2018
338    1439    Virginia Tech           1985          2018
339    1440              VMI           1985          2018
340    1441       W Carolina           1985          2018
341    1442       W Illinois           1985          2018
342    1443              WKU           1985          2018
343    1444       W Michigan           1985          2018
344    1445       W Salem St           2007          2010
345    1446      W Texas A&M           1985          1986
346    1447           Wagner           1985          2018
347    1448      Wake Forest           1985          2018
348    1449       Washington           1985          2018
349    1450    Washington St           1985          2018
350    1451         Weber St           1985          2018
351    1452    West Virginia           1985          2018
352    1453     WI Green Bay           1985          2018
353    1454     WI Milwaukee           1991          2018
354    1455       Wichita St           1985          2018
355    1456   William & Mary           1985          2018
356    1457         Winthrop           1987          2018
357    1458        Wisconsin           1985          2018
358    1459          Wofford           1996          2018
359    1460        Wright St           1988          2018
360    1461          Wyoming           1985          2018
361    1462           Xavier           1985          2018
362    1463             Yale           1985          2018
363    1464    Youngstown St           1985          2018

[364 rows x 4 columns]

In [140]:

events_2016

,EventID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,ElapsedSeconds,EventTeamID,EventPlayerID,EventType
0,15252382,2016,11,1104,1244,0,0,13,1104,631933,miss2_lay
1,15252383,2016,11,1104,1244,0,0,13,1104,631933,reb_off
2,15252384,2016,11,1104,1244,0,0,16,1244,634018,foul_pers
3,15252385,2016,11,1104,1244,0,0,16,1104,631933,miss1_free
4,15252386,2016,11,1104,1244,0,0,16,1104,631934,reb_dead
5,15252387,2016,11,1104,1244,0,0,16,1244,634018,reb_def
6,15252388,2016,11,1104,1244,0,0,29,1244,634015,turnover
7,15252389,2016,11,1104,1244,0,0,31,1104,631928,steal
8,15252390,2016,11,1104,1244,0,0,33,1244,634009,foul_pers
9,15252391,2016,11,1104,1244,0,0,43,1104,631926,miss2_jump
10,15252392,2016,11,1104,1244,0,0,43,1244,634014,reb_def
11,15252393,2016,11,1104,1244,0,0,54,1244,634018,miss2_jump
12,15252394,2016,11,1104,1244,0,0,54,1104,631928,reb_def
13,15252395,2016,11,1104,1244,0,0,64,1244,634014,foul_pers
14,15252396,2016,11,1104,1244,0,0,64,1104,631925,miss1_free
15,15252397,2016,11,1104,1244,0,0,64,1104,631934,reb_dead
16,15252398,2016,11,1104,1244,0,0,64,1244,634009,reb_def
17,15252399,2016,11,1104,1244,0,0,67,1104,631925,foul_pers
18,15252400,2016,11,1104,1244,0,0,75,1104,631933,block
19,15252401,2016,11,1104,1244,0,0,75,1244,634019,miss2_jump
20,15252402,2016,11,1104,1244,0,0,75,1244,634020,reb_off
21,15252403,2016,11,1104,1244,0,0,91,1244,634009,miss3_jump
22,15252404,2016,11,1104,1244,0,0,91,1104,631925,reb_def
23,15252405,2016,11,1104,1244,0,0,109,1244,634018,foul_pers
24,15252406,2016,11,1104,1244,1,0,109,1104,631926,made1_free
25,15252407,2016,11,1104,1244,2,0,109,1104,631926,made1_free
26,15252408,2016,11,1104,1244,0,0,132,1104,631926,foul_pers
27,15252409,2016,11,1104,1244,0,0,132,1244,634018,miss1_free
28,15252410,2016,11,1104,1244,0,0,132,1244,634020,reb_dead
29,15252411,2016,11,1104,1244,2,1,132,1244,634018,made1_free
...,...,...,...,...,...,...,...,...,...,...,...
2638249,17890631,2016,154,1437,1314,70,67,2307,1314,635115,made3_jump
2638250,17890632,2016,154,1437,1314,0,0,2310,1437,636951,sub_in
2638251,17890633,2016,154,1437,1314,0,0,2310,1437,636944,sub_out
2638252,17890634,2016,154,1437,1314,0,0,2310,1314,635117,timeout
2638253,17890635,2016,154,1437,1314,0,0,2325,1437,636944,sub_in
2638254,17890636,2016,154,1437,1314,0,0,2325,1437,636951,sub_out
2638255,17890637,2016,154,1437,1314,0,0,2325,1437,636942,turnover
2638256,17890638,2016,154,1437,1314,0,0,2334,1314,635109,assist
2638257,17890639,2016,154,1437,1314,70,69,2334,1314,635112,made2_jump
2638258,17890640,2016,154,1437,1314,0,0,2340,1437,636951,sub_in
2638259,17890641,2016,154,1437,1314,0,0,2340,1437,636944,sub_out
2638260,17890642,2016,154,1437,1314,0,0,2340,1437,636957,timeout
2638261,17890643,2016,154,1437,1314,0,0,2365,1314,635108,foul_pers
2638262,17890644,2016,154,1437,1314,71,69,2365,1437,636943,made1_free
2638263,17890645,2016,154,1437,1314,72,69,2365,1437,636943,made1_free
2638264,17890646,2016,154,1437,1314,0,0,2374,1314,635115,miss2_lay
2638265,17890647,2016,154,1437,1314,0,0,2374,1314,635115,reb_off
2638266,17890648,2016,154,1437,1314,72,71,2378,1314,635115,made2_lay
2638267,17890649,2016,154,1437,1314,0,0,2387,1314,635112,foul_pers
2638268,17890650,2016,154,1437,1314,0,0,2387,1437,636944,sub_in
2638269,17890651,2016,154,1437,1314,0,0,2387,1437,636943,sub_out
2638270,17890652,2016,154,1437,1314,0,0,2387,1437,636957,timeout
2638271,17890653,2016,154,1437,1314,73,71,2387,1437,636950,made1_free
2638272,17890654,2016,154,1437,1314,74,71,2387,1437,636950,made1_free
2638273,17890655,2016,154,1437,1314,74,74,2395,1314,635115,made3_jump
2638274,17890656,2016,154,1437,1314,0,0,2396,1437,636943,sub_in
2638275,17890657,2016,154,1437,1314,0,0,2396,1437,636944,sub_out
2638276,17890658,2016,154,1437,1314,0,0,2396,1437,636957,timeout
2638277,17890659,2016,154,1437,1314,0,0,2400,1437,636942,assist
2638278,17890660,2016,154,1437,1314,77,74,2400,1437,636951,made3_jump

In [141]:
regular_season_detailed_results

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
5,2003,11,1458,81,1186,55,H,0,26,57,...,11,12,17,6,22,8,19,4,3,25
6,2003,12,1161,80,1236,62,H,0,23,55,...,15,20,28,9,21,11,30,10,4,28
7,2003,12,1186,75,1457,61,N,0,28,62,...,17,17,23,8,25,10,15,14,8,18
8,2003,12,1194,71,1156,66,N,0,28,58,...,18,12,27,13,26,13,25,8,2,18
9,2003,12,1458,84,1296,56,H,0,32,67,...,14,7,12,9,23,10,18,1,3,18
10,2003,13,1166,106,1426,50,H,0,41,69,...,11,12,17,8,15,8,17,7,3,15
11,2003,13,1202,74,1106,73,N,0,29,51,...,22,5,5,13,16,15,12,6,2,12
12,2003,13,1237,66,1135,65,N,0,26,66,...,19,11,17,14,21,17,18,8,4,13
13,2003,13,1323,76,1125,48,H,0,25,56,...,24,4,8,14,26,12,17,10,0,17
14,2003,14,1125,83,1135,77,N,1,30,70,...,15,17,27,20,27,17,24,7,7,19
15,2003,14,1156,78,1236,71,N,0,27,46,...,20,18,24,6,17,21,11,5,1,21
16,2003,14,1161,81,1194,56,H,0,22,48,...,13,12,19,16,18,10,16,15,3,36
17,2003,14,1166,82,1202,57,H,0,33,61,...,11,9,14,13,23,9,26,8,4,18
18,2003,14,1183,73,1129,59,A,0,29,59,...,14,14,18,12,22,10,23,4,5,14
19,2003,14,1314,85,1336,55,H,0,32,60,...,23,10,11,15,20,6,13,7,5,19
20,2003,14,1323,89,1237,45,H,0,34,62,...,15,5,11,27,22,10,17,6,3,23
21,2003,14,1353,60,1162,36,H,0,23,57,...,8,9,13,11,23,4,27,2,4,19
22,2003,14,1390,61,1131,57,H,0,20,53,...,17,16,18,11,22,7,14,7,0,24
23,2003,14,1426,59,1106,47,N,0,25,53,...,18,1,2,8,15,10,8,10,6,14
24,2003,14,1462,87,1389,48,H,0,35,70,...,20,1,4,16,18,11,19,4,3,16
25,2003,15,1161,77,1156,63,H,0,27,58,...,13,14,20,7,19,13,13,6,6,22
26,2003,15,1194,93,1236,86,N,2,33,75,...,31,18,22,9,33,20,26,6,7,25
27,2003,15,1196,76,1256,55,H,0,28,48,...,5,16,22,12,17,14,22,8,2,22
28,2003,15,1242,81,1221,57,H,0,28,53,...,21,14,21,8,22,11,20,9,3,27
29,2003,15,1422,84,1447,65,H,0,33,53,...,25,10,16,14,15,9,12,10,2,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76606,2017,131,1153,81,1163,71,N,0,18,47,...,19,20,25,15,21,7,8,3,4,32
76607,2017,131,1181,75,1323,69,N,0,31,51,...,25,9,12,16,17,12,6,7,0,14
76608,2017,131,1235,80,1452,74,N,0,32,59,...,23,8,17,8,21,12,13,5,6,15
76609,2017,131,1245,70,1103,65,N,0,26,49,...,22,7,13,11,20,15,10,3,1,14
76610,2017,131,1246,79,1104,74,N,0,23,44,...,14,15,20,12,21,10,12,4,3,28
76611,2017,131,1276,84,1278,77,N,0,29,54,...,13,12,14,15,23,11,11,2,1,16
76612,2017,131,1292,83,1267,72,N,0,30,56,...,32,8,12,11,23,15,12,2,2,21
76613,2017,131,1300,67,1313,59,N,0,22,56,...,20,6,6,15,29,11,17,4,3,20
76614,2017,131,1305,79,1161,71,N,0,23,55,...,33,6,11,9,25,9,5,5,1,23
76615,2017,131,1308,70,1167,60,N,0,18,39,...,14,10,15,10,20,10,15,10,3,32
76616,2017,131,1309,68,1394,65,N,1,25,59,...,19,15,19,5,20,11,15,6,8,20
76617,2017,131,1315,93,1451,89,N,1,33,69,...,21,31,39,9,32,11,14,3,2,28
76618,2017,131,1343,72,1335,64,N,1,24,64,...,27,4,5,9,32,10,13,4,2,18
76619,2017,131,1348,84,1172,60,N,0,30,61,...,21,17,23,7,23,11,12,2,2,15
76620,2017,131,1374,70,1416,59,N,0,21,46,...,26,9,11,6,16,8,12,5,3,18
76621,2017,131,1402,83,1426,62,N,0,26,49,...,26,10,13,12,20,9,12,4,0,22
76622,2017,131,1407,74,1209,63,N,0,23,54,...,22,15,21,12,29,7,17,6,4,25
76623,2017,131,1411,53,1108,50,N,0,20,51,...,15,9,16,18,25,9,16,8,4,15
76624,2017,131,1413,50,1414,47,N,0,18,52,...,12,6,7,8,27,8,20,4,4,23
76625,2017,131,1433,87,1350,77,N,1,33,67,...,22,15,18,4,25,16,11,6,2,15
76626,2017,131,1436,56,1107,53,H,0,16,48,...,15,9,14,9,27,10,9,2,6,22
76627,2017,131,1437,74,1166,60,N,0,25,54,...,24,6,9,10,23,11,17,4,1,17
76628,2017,131,1458,76,1321,48,N,0,27,57,...,14,9,11,8,19,5,12,4,0,14
76629,2017,131,1463,73,1217,71,N,0,28,59,...,36,8,11,18,28,10,5,5,6,19
76630,2017,132,1246,82,1116,65,N,0,27,56,...,18,15,20,8,18,8,14,7,4,22
76631,2017,132,1276,71,1458,56,N,0,27,48,...,15,6,8,14,18,10,15,4,3,13
76632,2017,132,1343,71,1463,59,N,0,25,52,...,20,13,19,14,20,12,7,4,5,13
76633,2017,132,1348,70,1433,63,N,0,24,54,...,14,17,22,23,24,8,5,4,1,16
76634,2017,132,1374,71,1153,56,N,0,26,52,...,24,14,18,17,22,7,7,7,1,13
76635,2017,132,1407,59,1402,53,N,0,21,60,...,17,7,8,9,27,10,17,1,7,18

In [142]:
list(regular_season_detailed_results)

['Season',
 'DayNum',
 'WTeamID',
 'WScore',
 'LTeamID',
 'LScore',
 'WLoc',
 'NumOT',
 'WFGM',
 'WFGA',
 'WFGM3',
 'WFGA3',
 'WFTM',
 'WFTA',
 'WOR',
 'WDR',
 'WAst',
 'WTO',
 'WStl',
 'WBlk',
 'WPF',
 'LFGM',
 'LFGA',
 'LFGM3',
 'LFGA3',
 'LFTM',
 'LFTA',
 'LOR',
 'LDR',
 'LAst',
 'LTO',
 'LStl',
 'LBlk',
 'LPF']

In [143]:

regular_season_detailed_results_2003=regular_season_detailed_results.loc[regular_season_detailed_results['Season']==2003]

len(regular_season_detailed_results_2003.loc[regular_season_detailed_results_2003['WTeamID']==1393])/(len(regular_season_detailed_results_2003.loc[regular_season_detailed_results_2003['WTeamID']==1393])+len(regular_season_detailed_results_2003.loc[regular_season_detailed_results_2003['LTeamID']==1393]))

0.8275862068965517

In [144]:

GetWinningPercentage(2013,1393)

0.7428571428571429

In [145]:

def get_season(year):
    regular_season_detailed_results_year=regular_season_detailed_results.loc[regular_season_detailed_results['Season']==year]
    return regular_season_detailed_results_year

def get_winning_percentage(year,team):
    regular_season_detailed_results_year=get_season(year)
    result=len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])/(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    return result

def get_ppg(year,team):
    regular_season_detailed_results_year=get_season(year)
    total_points=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WScore'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LScore'])
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    ppg=total_points/games_played
    return ppg

def get_3_point_percentage(year,team):
    regular_season_detailed_results_year=get_season(year)
    total_3s_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGM3'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGM3'])
    total_3s_attempted=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGA3'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGA3'])
    return total_3s_made/total_3s_attempted

def get_field_goal_percentage(year,team):
    regular_season_detailed_results_year=get_season(year)
    total_field_goals_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGM'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGM'])
    total_field_goals_attempted=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGA'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGA'])
    return total_field_goals_made/total_field_goals_attempted

def get_free_throw_percentage(year,team):
    regular_season_detailed_results_year=get_season(year)
    total_free_throw_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFTM'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFTM'])
    total_free_throws_attempted=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFTA'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFTA'])
    return total_free_throw_made/total_free_throws_attempted

def get_field_goals_made_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    total_field_goals_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGM'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGM'])
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    return total_field_goals_made/games_played

def get_3_points_made_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_3s_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFGM3'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFGM3'])
    return total_3s_made/games_played

def get_free_throws_made_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_free_throws_made=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WFTM'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LFTM'])
    return total_free_throws_made/games_played

def get_off_rebounds_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_off_rebounds=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WOR'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LOR'])
    return total_off_rebounds/games_played

def get_def_rebounds_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_def_rebounds=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WDR'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LDR'])
    return total_def_rebounds/games_played

def get_assists_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_assists=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WAst'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LAst'])
    return total_def_rebounds/games_played

def get_turnovers_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_turnovers=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WTO'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LTO'])
    return total_turnovers/games_played

def get_steals_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_steals=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WStl'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LStl'])
    return total_steals/games_played

def get_blocks_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_blocks=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WBlk'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LBlk'])
    return total_blocks/games_played

def get_fouls_per_game(year,team):
    regular_season_detailed_results_year=get_season(year)
    games_played=(len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team])+len(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]))
    total_fouls=sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['WTeamID']==team]['WPF'])+sum(regular_season_detailed_results_year.loc[regular_season_detailed_results_year['LTeamID']==team]['LPF'])
    return total_fouls/games_played

get_fouls_per_game(2009,1393)

15.676470588235293

In [149]:
#Get Training Data 
#this will be gotten through regular season games 
def get_training_data():
    training_data=pd.DataFrame()
    training_data['Team1']=regular_season_detailed_results[['WTeamID','LTeamID']].min(axis=1)
    training_data['Team2']=regular_season_detailed_results[['WTeamID','LTeamID']].max(axis=1) 
    training_data['Year']=regular_season_detailed_results['Season']
    return training_data
td=get_training_data()
td['Team1WinningPercentage']=get_winning_percentage(td['Year'],td['Team1'])
td['Year'],td['Team1']
#get_winning_percentage(2017,1402)

(0        2003
 1        2003
 2        2003
 3        2003
 4        2003
 5        2003
 6        2003
 7        2003
 8        2003
 9        2003
 10       2003
 11       2003
 12       2003
 13       2003
 14       2003
 15       2003
 16       2003
 17       2003
 18       2003
 19       2003
 20       2003
 21       2003
 22       2003
 23       2003
 24       2003
 25       2003
 26       2003
 27       2003
 28       2003
 29       2003
          ...
 76606    2017
 76607    2017
 76608    2017
 76609    2017
 76610    2017
 76611    2017
 76612    2017
 76613    2017
 76614    2017
 76615    2017
 76616    2017
 76617    2017
 76618    2017
 76619    2017
 76620    2017
 76621    2017
 76622    2017
 76623    2017
 76624    2017
 76625    2017
 76626    2017
 76627    2017
 76628    2017
 76629    2017
 76630    2017
 76631    2017
 76632    2017
 76633    2017
 76634    2017
 76635    2017
 Name: Year, Length: 76636, dtype: int64, 0        1104
 1        1272
 2        1266
 3        1296
 4        1208
 5        1186
 6        1161
 7        1186
 8        1156
 9        1296
 10       1166
 11       1106
 12       1135
 13       1125
 14       1125
 15       1156
 16       1161
 17       1166
 18       1129
 19       1314
 20       1237
 21       1162
 22       1131
 23       1106
 24       1389
 25       1156
 26       1194
 27       1196
 28       1221
 29       1422
          ...
 76606    1153
 76607    1181
 76608    1235
 76609    1103
 76610    1104
 76611    1276
 76612    1267
 76613    1300
 76614    1161
 76615    1167
 76616    1309
 76617    1315
 76618    1335
 76619    1172
 76620    1374
 76621    1402
 76622    1209
 76623    1108
 76624    1413
 76625    1350
 76626    1107
 76627    1166
 76628    1321
 76629    1217
 76630    1116
 76631    1276
 76632    1343
 76633    1348
 76634    1153
 76635    1402
 Name: Team1, Length: 76636, dtype: int64)