In [143]:
import pandas as pd
#['Title','Date','?','URL','unknown','Action','Adventure','Animation','Children','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']

In [144]:
genre=pd.read_csv('Data/u.genre',sep='|',header=None)
info=pd.read_csv('Data/u.info',sep='|',header=None)
item=pd.read_csv('Data/u.item',sep='|',encoding='latin-1',header=None )
occupation=pd.read_csv('Data/u.occupation',sep='|',header=None)
user=pd.read_csv('Data/u.user',sep='|',header=None)
test_data=pd.read_csv('Data/u_test.data',sep='\t',header=None,index_col=0)
train_data=pd.read_csv('Data/u_train.data',sep='\t',header=None)

In [145]:
item.columns=['movie','Title','Date','?','URL','unknown','Action','Adventure','Animation','Children','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi','Thriller','War','Western']

In [146]:
item=item.drop('?',axis=1)

In [147]:
user.columns=['user','age','sex','occupation','zip']

In [148]:
test_data.columns=['user','movie']
train_data.columns=['user','movie','rating','time']

In [149]:
train_data=train_data.merge(item)

In [150]:
train_data=train_data.merge(user)

In [152]:
train_data=train_data.drop(['time','Title','URL','occupation','zip','Date'],axis=1)

In [153]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 80000 entries, 0 to 79999
Data columns (total 24 columns):
user           80000 non-null int64
movie          80000 non-null int64
rating         80000 non-null int64
unknown        80000 non-null int64
Action         80000 non-null int64
Adventure      80000 non-null int64
Animation      80000 non-null int64
Children       80000 non-null int64
Comedy         80000 non-null int64
Crime          80000 non-null int64
Documentary    80000 non-null int64
Drama          80000 non-null int64
Fantasy        80000 non-null int64
Film-Noir      80000 non-null int64
Horror         80000 non-null int64
Musical        80000 non-null int64
Mystery        80000 non-null int64
Romance        80000 non-null int64
Sci-Fi         80000 non-null int64
Thriller       80000 non-null int64
War            80000 non-null int64
Western        80000 non-null int64
age            80000 non-null int64
sex            80000 non-null object
dtypes: int64(23), object(1)
memory usage: 15.3+ MB

In [141]:
train_data

,user,movie,rating,Date,unknown,Action,Adventure,Animation,Children,Comedy,...,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,age,sex
0,196,242,3,24-Jan-1997,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
1,196,257,2,04-Jul-1997,0,1,1,0,0,1,...,0,0,0,0,1,0,0,0,49,M
2,196,111,4,26-Apr-1996,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
3,196,25,4,08-Mar-1996,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
4,196,382,4,01-Jan-1994,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
5,196,202,3,01-Jan-1993,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
6,196,153,5,01-Jan-1988,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
7,196,286,5,15-Nov-1996,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,49,M
8,196,66,3,01-Jan-1995,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
9,196,845,4,28-Sep-1996,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
10,196,173,2,01-Jan-1987,0,1,1,0,0,1,...,0,0,0,1,0,0,0,0,49,M
11,196,238,4,01-Jan-1987,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
12,196,94,3,01-Jan-1990,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,49,M
13,196,762,3,09-Feb-1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49,M
14,196,381,4,01-Jan-1994,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
15,196,306,4,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,49,M
16,196,8,5,01-Jan-1995,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,49,M
17,196,70,3,01-Jan-1994,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
18,196,655,5,01-Jan-1986,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,49,M
19,196,13,2,30-Oct-1995,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
20,196,692,5,01-Jan-1995,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
21,196,1022,4,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49,M
22,196,287,3,18-Dec-1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49,M
23,196,269,3,01-Jan-1997,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
24,196,285,5,04-Oct-1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49,M
25,196,251,3,11-Jul-1997,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
26,196,393,4,01-Jan-1993,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
27,196,663,5,01-Jan-1979,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
28,196,580,2,01-Jan-1995,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,49,M
29,196,428,4,01-Jan-1971,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,49,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79970,842,886,4,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,40,M
79971,842,313,4,01-Jan-1997,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,40,M
79972,842,754,1,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,40,M
79973,842,270,5,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,40,M
79974,842,362,3,06-Feb-1998,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,40,M
79975,842,1105,2,09-Jan-1998,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,40,M
79976,675,258,3,11-Jul-1997,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,34,M
79977,675,347,4,09-Jan-1998,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,34,M
79978,675,318,5,01-Jan-1993,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,34,M
79979,675,344,4,18-Dec-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79980,675,303,5,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79981,675,286,4,15-Nov-1996,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,34,M
79982,675,531,5,22-Nov-1996,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,34,M
79983,675,305,4,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79984,675,306,5,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,34,M
79985,675,900,4,25-Dec-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79986,675,509,5,01-Jan-1989,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79987,675,463,5,01-Jan-1994,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79988,675,937,1,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79989,675,1007,4,31-Jan-1997,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,34,M
79990,675,1101,4,01-Jan-1993,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,34,M
79991,675,312,2,01-Jan-1997,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,34,M
79992,675,874,4,08-Aug-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79993,675,311,3,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,34,M
79994,675,650,5,01-Jan-1957,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79995,675,896,5,01-Jan-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79996,675,891,2,18-Dec-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,34,M
79997,675,1255,1,02-May-1997,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79998,675,1628,5,01-Jan-1994,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M
79999,675,1653,5,27-Sep-1996,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,34,M